default: &default

rss_lists:
- name: "Miền Bắc"
  url: "http://ket-qua.com/rss/ket-qua-Xo-so-Mien-Bac-xsmb.rss"
  code: "MB"
- name: "Miền Nam"
  url: "http://ket-qua.com/rss/ket-qua-Xo-So-Mien-Nam-xsmn.rss"
  code: "MN"
- name: "Miền Trung"
  url: "http://ket-qua.com/rss/ket-qua-Xo-so-Mien-Trung-xsmt.rss"
  code: "MT"

district_lists:
- name: "Thừa Thiên Huế"
  code: "TTH"
- name: "Phú Yên"
  code: "PY"
- name: "Đắc Lắc"
  code: "DLK"
- name: "Quảng Nam"
  code: "QNM"
- name: "Đà Nẵng"
  code: "DNG"
- name: "Khánh Hoà"
  code: "KH"
- name: "Bình Định"
  code: "BDI"
- name: "Quãng Bình"
  code: "QB"
- name: "Quãng Trị"
  code: "QT"
- name: "Gia Lai"
  code: "GL"
- name: "Ninh Thuận"
  code: "NT"
- name: "Đắc Nông"
  code: "DNO"
- name: "Quãng Ngãi"
  code: "QNG"
- name: "Kon Tum"
  code: "KT"
- name: "TP.HCM"
  code: "HCM"
- name: "Cà Mau"
  code: "CM"
- name: "Đồng Tháp"
  code: "DT"
- name: "Bạc Liêu"
  code: "BL"
- name: "Bến Tre"
  code: "BT"
- name: "Vũng Tàu"
  code: "VT"
- name: "Cần Thơ"
  code: "CT"
- name: "Đồng Nai"
  code: "DN"
- name: "Sóc Trăng"
  code: "ST"
- name: "An Giang"
  code: "AG"
- name: "Bình Thuận"
  code: "BTH"
- name: "Tây Ninh"
  code: "TN"
- name: "Bình Dương"
  code: "BD"
- name: "Trà Vinh"
  code: "TV"
- name: "Vĩnh Long"
  code: "VL"
- name: "Bình Phước"
  code: "BP"
- name: "Hậu Giang"
  code: "HG"
- name: "Long An"
  code: "LA"
- name: "Kiên Giang"
  code: "KG"
- name: "Lâm Đồng"
  code: "LD"
- name: "Tiền Giang"
  code: "TG"

development:
  <<: *default
production:
  <<: *default