#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'locale', '~> 1.0.2'
cookbook 'apt', '~> 2.6.1'
cookbook 'build-essential', '~> 2.1.3'
cookbook 'git', '~> 4.1.0'

cookbook 'apache2', '~> 3.0.0'
cookbook 'postgresql'
cookbook 'imagemagick'
cookbook 'vim'
cookbook 'tmux'
cookbook 'ruby_build', '~> 0.8.0'

cookbook 'application_ruby', '~> 3.0.2'

cookbook 'nodejs', '~> 2.2.0'

cookbook 'user'

# App server cookbooks
cookbook 'rvm', '~> 0.9.2'

cookbook 'elasticsearch', '~> 0.3.13'

cookbook 'imagemagick', '~> 0.2.3'